### ISSUE TITLE
unable to uploaded after flashing ButtonTask on ATmega32u4 based Arduinos (Leonardo/ArduinoMicro)

### ISSUE THREAD

**Issue by waspinator** [Makuna/Task#3]
After uploading buttontask, everything seemed to work fine, LED lit up and serial messages appeared.

But trying to upload another sketch failed. Tried different computers, resetting the arduino, power cycling, but no go. Had to reburn the bootloader.

This was an Arduino Micro using Arduino 1.6.6

**Comment by Makuna** [comment]
The task library doesn't really do anything "risky" that could cause this.  If you look for Leonardo flashing issues, you will see that sometimes with them you have to try twice in row or hold the flash button or pull the Usb from computer and reinsert before flashing again.  Worst case like you have done, you have to burn the bootloader.  See[Leonardo Getting Started](https://www.arduino.cc/en/Guide/ArduinoLeonardoMicro) for more details on that. This is the same with the chip the Micro has and it will have similar issues.

I will try this on a Leonardo and see if I can reproduce.  I don't have the Micro.

Inside the buttontask.h file, you will see the following line, you could try increasing the timer from 3 to 10.  
```
Task(MsToTaskTime(3)), // check every three millisecond, 1-10 ms should be ok
```
This is along the thought that the USB software these chips use is taking cycles and this is just a little too fast for them.

Now where did I put that Leonardo??

**Comment by Makuna** [comment]
Confirmed that the same thing happens with the Leonardo.  As suggested in the link, one thing to try is to make sure there is this snippit of code at the top of the setup() so that the sketch waits long enough for the IDE to try to enter programming mode.

```
Serial.begin(57600);
while (!Serial); // wait for the serial to connect, 
```

**Comment by Makuna** [comment]
Rather than Burn Bootloader, the following steps will allow you to recover from this situation.
•Connect your Arduino via USB cable.
•Open the Arduino IDE and load the "Blink" example.
•Open the Tools/Port menu and see the normal serial port it uses.
•Now you must be fast: Reset the Arduino, and check which port it gets (for a very short period of time) and choose that port in the IDE under the menu Tools / Serial Port. You must do this before the Arduino disconnects again or else the correct menu point won't be accessible. You probably need one or two tries before you get it. That was the hard part.
•Press again Reset on the Arduino and, immediately after, press the Upload button in the Arduino IDE.
•Your Arduino should start the blink program shortly after the Upload and is "healed".

**Comment by Makuna** [comment]
There is nothing I can do to fix this.  I added a FAQ entry for this issue, and included the flash work around procedure so you don't need to Burn a new bootloader.
